language: java
  
branches:
  only:
    - master
    - stable

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

install: true

before_script:
    - psql -c 'create database gretl;' -U postgres
    - psql -c "CREATE ROLE ddluser WITH LOGIN PASSWORD 'ddluser';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE gretl TO ddluser;" -U postgres
    - psql -c "CREATE ROLE dmluser WITH LOGIN PASSWORD 'dmluser';" -U postgres
    - psql -c "CREATE ROLE readeruser WITH LOGIN PASSWORD 'readeruser';" -U postgres
    - psql -c 'select version();' -d gretl -U postgres
    - psql -c 'create extension postgis;' -d gretl -U postgres
    - psql -c 'create extension "uuid-ossp";' -d gretl -U postgres
    - psql -c 'select postgis_full_version();' -d gretl -U postgres
  
script: 
  - gradle -Dgretltest_dburi=jdbc:postgresql:gretl build dbTest publishMavenJavaPublicationToMavenLocal
  - gradle -Dgretltest_dburi=jdbc:postgresql:gretl --project-dir inttest testIntegration

deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} publishMavenJavaPublicationToPublicRepository
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} -Drelease=final publishMavenJavaPublicationToPublicRepository
    on:
      branch: stable
