sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master
    - stable
    - dockertravis
    - rename-postgres-db-stuff

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

install: true

before_script:
    - psql -c 'create database gretl;' -U postgres
    - psql -c "CREATE ROLE ddluser WITH LOGIN PASSWORD 'ddluser';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE gretl TO ddluser;" -U postgres
    - psql -c "CREATE ROLE dmluser WITH LOGIN PASSWORD 'dmluser';" -U postgres
    - psql -c "CREATE ROLE readeruser WITH LOGIN PASSWORD 'readeruser';" -U postgres
    - psql -c 'select version();' -d gretl -U postgres
    - psql -c 'create extension postgis;' -d gretl -U postgres
    - psql -c 'create extension "uuid-ossp";' -d gretl -U postgres
    - psql -c 'select postgis_full_version();' -d gretl -U postgres
  
script:
  - gradle -Pgretltest_dburi_pg=jdbc:postgresql:gretl build gretl:dbTest gretl:publishToMavenLocal
  - gradle -Pgretltest_dburi_pg=jdbc:postgresql:gretl --project-dir gretl/inttest testJar
  - cd runtimeImage/
  - ./build-gretl.sh $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER
  - cd ..
  - tooling/start-test-database-ora.sh background
  - gradle -Pgretltest_dburi_pg=jdbc:postgresql:gretl -Pgretltest_dburi_ora=jdbc:oracle:thin:@localhost:1521:xe --project-dir gretl/inttest testImage

deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} gretl:publishMavenJavaPublicationToPublicRepository
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} -Drelease=final gretl:publishMavenJavaPublicationToPublicRepository
    on:
      branch: stable
  - provider: script
    skip_cleanup: true
    script: runtimeImage/push-gretl.sh $dockerhub_pwd
    on:
      branch: master
