apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gretl-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: gretl
    name: gretl
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: gretl
    name: gretl
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'gretl:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
  status:
    lastVersion: 0
