apiVersion: v1
kind: Template
labels:
  app: gretl-platform
metadata:
  creationTimestamp: null
  name: gretl-platform
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      role: jenkins-slave
    name: gretl
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: ImageStreamTag
        name: ${GRETL_RUNTIME_IMAGE}
        namespace: ${GRETL_BUILD_PROJECT}
      name: latest
parameters:
- name: GRETL_RUNTIME_IMAGE
  description: Imagestream tag of GRETL runtime to be pulled from build project.
  displayName: imagestream of GRETL runtime
  value: gretl:latest
- name: GRETL_BUILD_PROJECT
  description: OpenShift build project containing the imagestream of the GRETL runtime.
  displayName: GRETL runtime build project
  value: gretl-build
